// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createClass = `-- name: CreateClass :one
INSERT INTO classes(id, name)
VALUES ($1, $2)
RETURNING id, name
`

type CreateClassParams struct {
	ID   uuid.UUID `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRowContext(ctx, createClass, arg.ID, arg.Name)
	var i Class
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteClassByID = `-- name: DeleteClassByID :exec
DELETE FROM classes
WHERE id = $1
`

func (q *Queries) DeleteClassByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteClassByID, id)
	return err
}
