// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Name      string `json:"name"`
	Login     string `json:"login"`
	Password  string `json:"-"`
	Role      string `json:"role"`
	GroupID   uuid.NullUUID `json:"group_id"`
}

type Group struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Code      string
}

type Class struct {
	ID   uuid.UUID `json:"id"`
	Name string `json:"name"`
}

type SemesterActivity struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	ClassID   uuid.UUID `json:"class_id"`
	GroupID   uuid.UUID `json:"group_id"`
	TeacherID uuid.UUID `json:"teacher_id"`
}