// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: query.sql

package db

import (
	"context"
)

const clearStreamsTable = `-- name: clearStreamsTable :exec
DELETE from streams
`

func (q *Queries) ClearStreamsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearStreamsTable)
	return err
}
