// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: query.sql

package db

import (
	"context"
	"github.com/google/uuid"
)

const clearStreamsTable = `-- name: clearStreamsTable :exec
DELETE from streams
`

func (q *Queries) ClearStreamsTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearStreamsTable)
	return err
}

const getStreamByID = `-- name: GetStreamByID :one
SELECT name
from streams
where id = $1
`

func (q *Queries) GetStreamByID(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getStreamByID, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
