// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: query.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(
        id,
        created_at,
        updated_at,
        name,
        login,
        password,
        role,
        group_id
    )
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8
    )
RETURNING id, created_at, updated_at, name, login, password, role, group_id
`

type CreateUserParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Login     string
	Password  string
	Role      string
	GroupID   uuid.NullUUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Login,
		arg.Password,
		arg.Role,
		arg.GroupID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Login,
		&i.Password,
		&i.Role,
		&i.GroupID,
	)
	return i, err
}

const getUserByCredentials = `-- name: GetUserByCredentials :one
SELECT id, created_at, updated_at, name, login, password, role, group_id
FROM users
WHERE login = $1
    and password = $2
`

type GetUserByCredentialsParams struct {
	Login    string
	Password string
}

func (q *Queries) GetUserByCredentials(ctx context.Context, arg GetUserByCredentialsParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByCredentials, arg.Login, arg.Password)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Login,
		&i.Password,
		&i.Role,
		&i.GroupID,
	)
	return i, err
}

const getUserById = `-- name: GetUserById :one
SELECT id, created_at, updated_at, name, login, password, role, group_id
FROM users
WHERE id = $1
`

func (q *Queries) GetUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Login,
		&i.Password,
		&i.Role,
		&i.GroupID,
	)
	return i, err
}

const updateStudentsGroup = `-- name: UpdateStudentsGroup :one
UPDATE users
SET group_id = $2,
    updated_at = NOW()
WHERE id = $1
    and role = "student"
RETURNING id, created_at, updated_at, name, login, password, role, group_id
`

type UpdateStudentsGroupParams struct {
	ID      uuid.UUID
	GroupID uuid.NullUUID
}

func (q *Queries) UpdateStudentsGroup(ctx context.Context, arg UpdateStudentsGroupParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateStudentsGroup, arg.ID, arg.GroupID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Login,
		&i.Password,
		&i.Role,
		&i.GroupID,
	)
	return i, err
}
